#Demo pipeline

trigger:
  branches:
    include:
      - master

pr:
  branches:
    include:
      - master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: 'Junit'
    displayName: 'junit-test'
    jobs:
      - job: 'junit-test'
        displayName: 'Running unit test'
        steps:
         - script: echo 'Running unit test'
           inputs:
             mavenPomFile: 'pom.xml'
             publishJUnitResults: true
             testResultsFiles: '**/surefire-reports/TEST-*.xml'
             codeCoverageToolOption: 'JaCoCo'
             javaHomeOption: 'JDKVersion'
             mavenVersionOption: 'Default'
             mavenAuthenticateFeed: false
             effectivePomSkip: false
             sonarQubeRunAnalysis: true
             isJacocoCoverageReportXML: true
             sqMavenPluginVersionChoice: 'latest'
             checkStyleRunAnalysis: true
             pmdRunAnalysis: true
             findBugsRunAnalysis: true